# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog

from gui.dialog_ui import Ui_Dialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, BGMs):
        MainWindow.setObjectName("抖音BGM推荐系统")
        MainWindow.resize(444, 406)
        self.BGM = BGMs
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setIconSize(QtCore.QSize(30, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 170, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.showChildren)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抖音BGM推荐系统"))
        self.comboBox.setItemText(0, _translate("MainWindow", "化妆品"))
        self.comboBox.setItemText(1, _translate("MainWindow", "日用品"))
        self.comboBox.setItemText(2, _translate("MainWindow", "食品"))
        self.comboBox.setItemText(3, _translate("MainWindow", "家具"))
        self.comboBox.setItemText(4, _translate("MainWindow", "花鸟绿植"))
        self.comboBox.setItemText(5, _translate("MainWindow", "母婴"))
        self.comboBox.setItemText(6, _translate("MainWindow", "书籍"))
        self.comboBox.setItemText(7, _translate("MainWindow", "衣物"))
        self.comboBox.setItemText(8, _translate("MainWindow", "数码"))
        self.pushButton.setText(_translate("MainWindow", "确认"))

    # 显示第二视图
    def showChildren(self):
        # 窗口初始属性
        child = QDialog()
        child_ui = Ui_Dialog()
        child_ui.setupUi(child, self.comboBox.currentIndex(), self.BGM[self.comboBox.currentIndex()])
        child.setWindowTitle("推荐结果")
        child.setWindowModality(Qt.ApplicationModal)

        child.exec_()
